spring.application.name=IntroSpring


spring.jpa.hibernate.ddl-auto=create
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ZjqEG2VXzn0I
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://ep-damp-pine-a5uprxi3-pooler.us-east-2.aws.neon.tech/neondb
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always
#espera a que to do haya sido cargado
spring.jpa.defer-datasource-initialization=true

